---
kind: pipeline
name: default

steps:
- name: build
  image: golang
  commands:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - CGO_ENABLED=0 GOOS=linux go build -a -o drone-dingtalk-message .
  - ./drone-dingtalk-message
- name: publish
  image: plugins/docker
  when:
    branch:
    - beta
    status:
    - success
    event:
    - push
  settings:
    repo: lddsb/drone-dingtalk-message
    dockerfile: Dockerfile
    tags: beta
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

