### [**[TPL_REPO_SHORT_NAME]**] build #[TPL_BUILD_NUMBER] [TPL_BUILD_STATUS] (`takes [TPL_BUILD_CONSUMING]s`)

Action: [TPL_BUILD_EVENT] @ [TPL_COMMIT_BRANCH]

> [TPL_COMMIT_MSG]

Commit: [[TPL_COMMIT_SHA]]([TPL_COMMIT_LINK])

[[TPL_AUTHOR_NAME]([TPL_AUTHOR_EMAIL])](mailto:[TPL_AUTHOR_EMAIL])

[🔗 CI Detail]([TPL_BUILD_LINK])